spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=30m

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# logging:
#   level:
#     org.springframework.web: INFO
#     com.mobiauto: DEBUG